apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xresourcgroup-composition-ref
  namespace: ucplearn
  labels:
    provider: azure
  annotations:
    resource.platform.volvocars.com/external-name: composition-azure-custom-resourcegroup
spec:
  compositeTypeRef:
    apiVersion: resource.platform.volvocars.com/v1alpha1
    kind: XResourcGroup
  resources:
      - name: myresourcegroup
        base: 
          apiVersion: azure.upbound.io/v1beta1
          kind: ResourceGroup
          spec:
            forProvider:
              location: West Europe
              tags:
                provisioner: crossplane-composition
                application: ucplearn
            providerConfigRef:
              name: azure