apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcustomeresourcgroup
  annotations:
    resource.platform.volvocars.com/external-name: azure-custom-resourcegroup
  labels:
    guide: ucplearn
spec:
  group: resource.platform.volvocars.com
  names:
    kind: XResourcGroup
    plural: xresourcgroups
  claimNames:
    kind: CustomResourcGroup
    plural: customresourcegroups
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object