apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-ucp-crossplane-demo
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
      application: ucplearn
      name: demo
