apiVersion: azure.upbound.io/v1beta1
metadata:
  name: azure
  annotations:
    provider.platform.volvocars.com/external-name: azure-provider
  labels:
    environment: development
    provider: azure
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-secret
      key: creds