apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-ucp-crossplane-learn
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
      application: ucplearn
  # the spec.providerConfigRef.name must match the ProviderConfig metadata.name value.
  providerConfigRef:
    name: azure
