apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgres-composition-ref
  labels:
    provider: default
    guide: ucplearn
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.postgresql.platform.volvocars.com/v1alpha1
    kind: XCompositePostgreSQLInstance
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels  
  resources:
    # db-server
    - name: postgresqlserver
      base:
        apiVersion: database.azure.crossplane.io/v1beta1
        kind: PostgreSQLServer
        spec:
          forProvider:
            createMode: Default
            administratorLogin: ucplearnadmin
            resourceGroupName: rg-ucp-crossplane-learn
            minimalTlsVersion: TLS1_2
            sslEnforcement: Enabled
            sku:
              tier: GeneralPurpose
              capacity: 2
              family: Gen5  
            storageProfile:
              backupRetentionDays: 35
              geoRedundantBackup: Disabled
              storageAutogrow: Disabled
          writeConnectionSecretToRef:
            namespace: crossplane-system
          providerConfigRef:
            name: default
      patches:
      - type: PatchSet
        patchSetName: Metadata
      - fromFieldPath: "metadata.uid"
        toFieldPath: "spec.writeConnectionSecretToRef.name"
        transforms:
        - type: string
          string:
            fmt: "postgresqlserver-admin-%s"
      - fromFieldPath: "spec.parameters.version"
        toFieldPath: "spec.forProvider.version"
      - fromFieldPath: "spec.parameters.location"
        toFieldPath: "spec.forProvider.location"
      - fromFieldPath: "spec.parameters.storageGB"
        toFieldPath: "spec.forProvider.storageProfile.storageMB"
        transforms:
          - type: math
            math:
              multiply: 1024